branches:
  only:
    - master
language: python
python:
  - 2.7
install: python setup.py install
before_script:
  - pip install mozdownload==1.9
  - mozdownload -t daily -a b2g -p linux64 -l multi
  - tar xvjf *.multi.linux-x86_64.tar.bz2
  - sh -e /etc/init.d/xvfb start
  - sleep 10
script: gaiatest --app=b2gdesktop --binary=b2g/b2g-bin --profile=b2g/gaia/profile --type=b2g-xfail --restart gaiatest/tests/manifest.ini
env:
  - DISPLAY=':99.0' GAIATEST_ACKNOWLEDGED_RISKS=true GAIATEST_SKIP_WARNING=true
notifications:
  email:
    - webqa-ci@mozilla.org
  irc:
    - "irc.mozilla.org#automation"
    - "irc.mozilla.org#mozwebqa"
