branches:
  only:
    - master
language: python
python:
  - 2.7
install: python setup.py install
before_script:
  - curl -k -L -O https://ftp.mozilla.org/pub/mozilla.org/b2g/nightly/latest-mozilla-central/b2g-25.0a1.multi.linux-x86_64.tar.bz2
  - tar xvjf b2g-25.0a1.multi.linux-x86_64.tar.bz2
  - sh -e /etc/init.d/xvfb start
  - sleep 10
  - echo "{\"acknowledged_risks\":true,\"skip_warning\":true}" > testvars.json
script: gaiatest --app=b2gdesktop --binary=b2g/b2g-bin --profile=b2g/gaia/profile --testvars=testvars.json --type=b2g-xfail --restart gaiatest/tests/manifest.ini
env:
  - DISPLAY=':99.0'
notifications:
  email:
    - webqa-ci@mozilla.org
  irc:
    - "irc.mozilla.org#automation"
    - "irc.mozilla.org#mozwebqa"
